name: Update formula

on:
  pull_request:
    types:
      - opened
      - synchronize
      - labeled
      - reopened

jobs:

  build:
    name: Update formula
    # ...and not contains ready-for/testing
    if: contains(github.event.pull_request.labels.*.name, 'type/renovate') && !contains(github.event.pull_request.labels.*.name, 'ready-for/testing')
    runs-on: ubuntu-20.04
    steps:

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Update formula
        id: update-formula
        env:
          PR: ${{ github.event.pull_request.number }}
        run: |
          echo "Running for PR #${PR}"

          FILES=$(
              curl "https://api.github.com/repos/${GITHUB_REPOSITORY}/pulls/${PR}/files" \
                      --silent \
                      --location \
                      --header 'Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' | \
                  jq --raw-output '.[].filename'
          )
          STARTS_WITH="renovate/"
          for FILE in ${FILES}; do
              if test "${FILE:0:${#STARTS_WITH}}" == "${STARTS_WITH}"; then
                  echo "Updating ${FILE}"
                  bash "${FILE}"
              fi
          done

      - name: Commit changes
        id: add-and-commit
        uses: EndBug/add-and-commit@v7
        with:
          add: 'Formula/*.rb'
          message: 'Updated formulae'
